config/routes.rb
Rails.application.routes.draw do
  get 'participations/create'
  get 'participations/update'
  get 'top/main'
  get 'top/login'
  post '/top/login', to: 'top#login'
  get 'top/logout'
  resources :users
  resources :user_profiles,only: [:edit,:index,:show,:update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #root "users#index"
  #root 'fishing_trips#index'
  root 'top#main'
  resources :fishing_trips, only: [:new, :create, :index, :destroy]
  resources :participations, only: [:create, :update]
  resources :chat_rooms, only: [:show] do
    resources :messages, only: [:create]
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
    belongs_to :user, dependent: :destroy
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def index
    @user_profiles = UserProfile.all
  end
  
  def show
    @user_profile = UserProfile.find_by(user_id: params[:id])
  end

  def edit
    @user_profile = UserProfile.find_by(user_id: params[:id])
  end
  
  def update
      @user_profile = UserProfile.find_by(user_id: params[:id])
      if @user_profile.update(age: params[:user_profile][:age],biography: params[:user_profile][:biography],region: params[:user_profile][:region],experience_years: params[:user_profile][:experience_years],favorite_fishing_type: params[:user_profile][:favorite_fishing_type])
        @user_profile.save
        redirect_to user_profile_path
      else
        render "edit"
      end
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/edit.html.erb
<h1>プロフィール編集画面</h1>
<%= form_for @user_profile , url: {action: :update} do |f| %>
    <div class="form-group">
        <%= f.label :age, '年齢' %>
        <%= f.text_field :age, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :biography, '自己紹介文' %>
        <%= f.text_field :biography, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :region, '地域' %>
        <%= f.text_field :region, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :experience_years, '経験年数' %>
        <%= f.text_field :experience_years, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :favorite_fishing_type, '好きな釣りの種類' %>
        <%= f.text_field :favorite_fishing_type, class: 'form-control' %>
    </div>
    <div class="d-flex justify-content-end mt-3">
        <%= f.submit '更新' %>        
    </div>

<% end %>

app/views/user_profiles/show.html.erb
<div class="container mt-4">

  <!-- User Profile Information -->
  <h1><%= @user_profile.user.username %></h1>

  <!-- Profile Details -->
  <div class="row mt-4">
    <div class="col-md-6">
      <strong>年齢:</strong> <%= @user_profile.age %><br>
      <strong>自己紹介文:</strong> <%= @user_profile.biography %><br>
      <strong>地域:</strong> <%= @user_profile.region %><br>
      <strong>釣りの経験年数:</strong> <%= @user_profile.experience_years %><br>
      <strong>好きな釣りの種類:</strong> <%= @user_profile.favorite_fishing_type %><br>
    </div>
  </div>

  <!-- Edit Profile Link -->
  <div class="mt-4">
    <%= link_to "戻る", fishing_trips_path, class: "btn btn-secondary" %>
    <%= link_to "プロフィールを編集する", edit_user_profile_path(current_user.id), class: "btn btn-primary" %>
  </div>

</div>