config/routes.rb
Rails.application.routes.draw do
  get 'participations/create'
  get 'participations/update'
  get 'top/main'
  get 'top/login'
  post '/top/login', to: 'top#login'
  get 'top/logout'
  resources :users
  resources :user_profiles,only: [:edit,:index,:show,:update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #root "users#index"
  #root 'fishing_trips#index'
  root 'top#main'
  resources :fishing_trips, only: [:new, :create, :index, :destroy]
  resources :participations, only: [:create, :update]
  resources :chat_rooms, only: [:show] do
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :fishing_trip
  has_many :messages, dependent: :destroy
end

app/models/fishing_trip.rb
class FishingTrip < ApplicationRecord
  belongs_to :organizer, class_name: 'User', foreign_key: 'organizer_id'
  has_many :participations, dependent: :destroy
  has_one :chat_room, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :fishing_trip
  
  enum status: { pending: 0, approved: 1, declined: 2, cancelled: 3 }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :organized_fishing_trips, class_name: 'FishingTrip', foreign_key: 'organizer_id', dependent: :destroy
    has_many :participations, dependent: :destroy
    has_one :user_profile, dependent: :destroy
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
    belongs_to :user, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    private
        def current_user
            if session[:login_uid]
                User.find_by(username: session[:login_uid])
            end
        end

                
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def show
    #@chat_room = ChatRoom.find(params[:id])
    @chat_room = ChatRoom.find(params[:id])
    if @chat_room.nil?
      # ここでリダイレクト先のパスを指定します（例: root_pathやfishing_trips_pathなど）
      redirect_to root_path, alert: 'チャットルームが見つかりません。'
    else
      @messages = @chat_room.messages
      @message = Message.new
    end
  end
end

app/controllers/fishing_trips_controller.rb
class FishingTripsController < ApplicationController
    
    
    def index
        # @変数名 ⇦ インスタンス変数：ビューなどの他の場所でも利用することが出来る
        # @変数名 = {} ⇦ 空のハッシュで初期化、ハッシュはキーと値のペアを格納するためのデータ構造
        @fishing_trips = FishingTrip.all #FishingTripモデルの全てのレコードをDBから取得
        @other_trips = FishingTrip.all #FishingTripモデルの全てのレコードをDBから取得
        @is_organizer = {} #募集の主催者が現在のユーザーかどうかの真偽値を保持

        @user_participation_status = {}
        @each_all_participations = {} #各募集に対する全参加申請
        @current_user_participations = {} #現在のユーザーの参加申請
        
        @fishing_trips.each do |trip|
           @is_organizer[trip.id] = trip.organizer == current_user
           @current_user_participations[trip.id] = trip.participations.where(user: current_user)
            if @is_organizer[trip.id] #もし主催者であれば、
                @each_all_participations[trip.id] = trip.participations #そのすべての参加情報を保存
            else #主催者でなければ
                participation = trip.participations.find_by(user: current_user) #そのユーザーに関連する参加情報を検索
                @user_participation_status[trip.id] = participation&.status #見つかった参加情報のステータスを取得
            end
        end
        # パラメータで都道府県が指定されていれば、それに基づいてフィルタリング
        if params[:location].present? #リクエストのパラメータに'location'キーが存在し、かつそれに値が設定されている(空ではない)場合にtrueを返す
            @other_trips = @other_trips.where(location: params[:location])#location 属性がリクエストの location パラメータと一致する FishingTrip レコードのみを選択する
        end
    end
    
    
    def new
        @fishing_trip = FishingTrip.new
    end
    
    
    def create
        @fishing_trip = FishingTrip.new(fishing_trip_params)
        @fishing_trip.organizer = current_user #現在ログインしているユーザーを設定
        if @fishing_trip.save
            @chat_room = ChatRoom.new(fishing_trip_id: @fishing_trip.id)
            if @chat_room.save
                redirect_to fishing_trips_path, notice: '募集とチャットルームが作成されました。'
            else
                redirect_to new_fishing_trip_path, alert: 'チャットルームの作成に失敗しました'
            end
        else
            render :new
        end
        
    end
    
    def destroy
        @fishing_trip = FishingTrip.find(params[:id])
        @fihsing_trip.destroy
        redirect_to fishing_trips_path, notice: '募集が削除されました'
    end
    
    private
        def fishing_trip_params
            params.require(:fishing_trip).permit(:organizer_id, :title, :description, :location, :start_date, :participant_limit)
        end
        
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @message = @chat_room.messages.new(message_params)
    @message.user = current_user

    if @message.save
      redirect_to chat_room_path(@chat_room)
    else
      # エラーハンドリング（必要に応じて）
      redirect_to chat_room_path(@chat_room), alert: 'メッセージの送信に失敗しました。'
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    render "login"
  end

  def login
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:login_uid] = user.username
      redirect_to fishing_trips_path
    else
      flash[:alert] = 'ユーザー名またはパスワードが正しくありません。'
      render "login"
    end
  end

  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def index
    @user_profiles = UserProfile.all
  end
  
  def show
    @user_profile = UserProfile.find_by(user_id: params[:id])
  end

  def edit
    @user_profile = UserProfile.find_by(user_id: params[:id])
  end
  
  def update
      @user_profile = UserProfile.find_by(user_id: params[:id])
      if @user_profile.update(age: params[:user_profile][:age],biography: params[:user_profile][:biography],region: params[:user_profile][:region],experience_years: params[:user_profile][:experience_years],favorite_fishing_type: params[:user_profile][:favorite_fishing_type])
        @user_profile.save
        redirect_to user_profile_path
      else
        render "edit"
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def new
    @user=User.new
    @user_profile=UserProfile.new
  end
  
  def create
      if User.exists?(username: params[:user][:username])
        redirect_to new_user_path
      else
        @user = User.new(user_params)
        if @user.save
          @user_profile = UserProfile.new(user_profile_params)
          @user_profile.user_id = @user.id # UserとUserProfileを関連付ける
          @user_profile.save
          redirect_to top_login_path
          # 保存が成功した場合の処理
        else
          redirect_to new_user_path
        # 保存が失敗した場合の処理
        end
      end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, user_profile_attributes: [:age, :biography, :region, :experience_years, :favorite_fishing_type])
  end

  def user_profile_params
    params.require(:user).require(:user_profile).permit(:age, :biography, :region, :experience_years, :favorite_fishing_type)
  end
  
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/fishing_trips_helper.rb
module FishingTripsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container">
      <% if session[:login_uid] %>
        <%= link_to 'FishingTrip', fishing_trips_path,  class: "navbar-brand" %>
      <% else %>
        <%= link_to 'FishingTrip', top_login_path,  class: "navbar-brand" %>
      <% end %>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
        <% if session[:login_uid] && current_user %>
            <li>
                <%= link_to fishing_trips_path, class: "nav-link text-light" do %>
                    <i class="bi bi-house"></i> ホーム
                <% end %>
            </li>
            <li>
                <%= link_to top_logout_path, class: "nav-link text-light" do %>
                    <i class="bi bi-box-arrow-left"></i> ログアウト
                <% end %>
            </li>
            <li>
                <%= link_to user_profile_path(current_user.id), class: "nav-link text-light" do %>
                    <i class="bi bi-person-circle"></i> <%= current_user.username %>
                <% end %>
            </li>

        <% else %>
            <li>
                <%= link_to '会員登録', new_user_path, class: "nav-link text-light" %>
            </li>
            <li>
                <%= link_to 'ログイン', top_login_path, class: "nav-link text-light" %>
            </li>

        <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/application/_sub-header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container collapse navbar-collapse justify-content-around">
        <ul class="nav nav-tabs">
        <% if session[:login_uid] %>
            <li class="nav-item">
                <%= link_to '#other-fishing-trips', class: "nav-link active text-light", data: { toggle: 'tab' } do %>
                    <i class="bi bi-house"></i> 他人の釣り募集
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to '#pending-fishing-trips', class: "nav-link text-light", data: { toggle: 'tab' } do %>
                    <i class="bi bi-box-arrow-left"></i> 参加申請中
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to '#approved-fishing-trips', class: "nav-link text-light", data: { toggle: 'tab' } do %>
                    <i class="bi bi-person-circle"></i> 参加予定
                <% end %>
            </li>
            <li class="nav-item">
                <%= link_to '#my-fishing-trips', class: "nav-link text-light", data: { toggle: 'tab' } do %>
                    <i class="bi bi-box-arrow-left"></i> 自分の募集
                <% end %>
            </li>
        <% end %>
        </ul>
    </div>
</nav>

app/views/top/login.html.erb
<div class="container mt-2">
    <h1>ログイン</h1>
    <%= form_with url: top_login_path, local: true do |form| %>
        <div class="form-group">
            <%= form.label :username, 'ユーザーID' %>
            <%= form.text_field :username, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= form.label :password, 'パスワード' %>
            <%= form.password_field :password, class: 'form-control' %>
        </div>
        <div class="d-flex justify-content-end mt-2">
            <%= form.submit 'ログイン', class: 'btn btn-primary form-submit-button justify-content-end' %>    
        </div>
    <% end %>

    <div class="d-flex justify-content-end mt-1">
        <%= link_to '新規登録はこちら', new_user_path, class: 'btn btn-link' %>
    </div>        
</div>

app/views/top/logout.html.erb
<h1>Top#logout</h1>
<p>Find me in app/views/top/logout.html.erb</p>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>