config/routes.rb
Rails.application.routes.draw do
  get 'participations/create'
  get 'participations/update'
  get 'top/main'
  get 'top/login'
  post '/top/login', to: 'top#login'
  get 'top/logout'
  resources :users
  resources :user_profiles,only: [:edit,:index,:show,:update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #root "users#index"
  #root 'fishing_trips#index'
  root 'top#main'
  resources :fishing_trips, only: [:new, :create, :index, :destroy]
  resources :participations, only: [:create, :update]
  resources :chat_rooms, only: [:show] do
    resources :messages, only: [:create]
  end
end

app/models/fishing_trip.rb
class FishingTrip < ApplicationRecord
  belongs_to :organizer, class_name: 'User', foreign_key: 'organizer_id'
  has_many :participations, dependent: :destroy
  has_one :chat_room, dependent: :destroy
end

app/controllers/fishing_trips_controller.rb
class FishingTripsController < ApplicationController
    
    
    def index
        # @変数名 ⇦ インスタンス変数：ビューなどの他の場所でも利用することが出来る
        # @変数名 = {} ⇦ 空のハッシュで初期化、ハッシュはキーと値のペアを格納するためのデータ構造
        @fishing_trips = FishingTrip.all #FishingTripモデルの全てのレコードをDBから取得
        @other_trips = FishingTrip.all #FishingTripモデルの全てのレコードをDBから取得
        @is_organizer = {} #募集の主催者が現在のユーザーかどうかの真偽値を保持

        @user_participation_status = {}
        @each_all_participations = {} #各募集に対する全参加申請
        @current_user_participations = {} #現在のユーザーの参加申請
        
        @fishing_trips.each do |trip|
           @is_organizer[trip.id] = trip.organizer == current_user
           @current_user_participations[trip.id] = trip.participations.where(user: current_user)
            if @is_organizer[trip.id] #もし主催者であれば、
                @each_all_participations[trip.id] = trip.participations #そのすべての参加情報を保存
            else #主催者でなければ
                participation = trip.participations.find_by(user: current_user) #そのユーザーに関連する参加情報を検索
                @user_participation_status[trip.id] = participation&.status #見つかった参加情報のステータスを取得
            end
        end
        # パラメータで都道府県が指定されていれば、それに基づいてフィルタリング
        if params[:location].present? #リクエストのパラメータに'location'キーが存在し、かつそれに値が設定されている(空ではない)場合にtrueを返す
            @other_trips = @other_trips.where(location: params[:location])#location 属性がリクエストの location パラメータと一致する FishingTrip レコードのみを選択する
        end
    end
    
    
    def new
        @fishing_trip = FishingTrip.new
    end
    
    
    def create
        @fishing_trip = FishingTrip.new(fishing_trip_params)
        @fishing_trip.organizer = current_user #現在ログインしているユーザーを設定
        if @fishing_trip.save
            @chat_room = ChatRoom.new(fishing_trip_id: @fishing_trip.id)
            if @chat_room.save
                redirect_to fishing_trips_path, notice: '募集とチャットルームが作成されました。'
            else
                redirect_to new_fishing_trip_path, alert: 'チャットルームの作成に失敗しました'
            end
        else
            render :new
        end
        
    end
    
    def destroy
        @fishing_trip = FishingTrip.find(params[:id])
        @fihsing_trip.destroy
        redirect_to fishing_trips_path, notice: '募集が削除されました'
    end
    
    private
        def fishing_trip_params
            params.require(:fishing_trip).permit(:organizer_id, :title, :description, :location, :start_date, :participant_limit)
        end
        
end

app/helpers/fishing_trips_helper.rb
module FishingTripsHelper
end

app/views/fishing_trips/index.html.erb
<div class="tab-content">
  <div class="tab-pane fade show active mt-3" id="other-fishing-trips">
    <h2>他人の釣り募集一覧</h2>
    
    <% filter = @fishing_trips.select { |trip| current_user != trip.organizer && @user_participation_status[trip.id] != 'approved' && @user_participation_status[trip.id] != 'declined' && @user_participation_status[trip.id] != 'pending' } %>
    <% if filter.any? %>
      <!-- location:フィルターの表示  -->
      <%= form_with url: fishing_trips_path, method: :get, local: true, id: 'location-filter-form' do |form| %>
      <%= form.label :location, '都道府県で絞り込む:' %>
      <%= form.select :location, [
        ['すべて', ''],
        '北海道', '青森県', '岩手県', '宮城県', '秋田県', 
        '山形県', '福島県', '茨城県', '栃木県', '群馬県', 
        '埼玉県', '千葉県', '東京都', '神奈川県', '新潟県', 
        '富山県', '石川県', '福井県', '山梨県', '長野県', 
        '岐阜県', '静岡県', '愛知県', '三重県', '滋賀県', 
        '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県', 
        '鳥取県', '島根県', '岡山県', '広島県', '山口県', 
        '徳島県', '香川県', '愛媛県', '高知県', '福岡県', 
        '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', 
        '鹿児島県', '沖縄県'
      ], selected: params[:location], include_blank: true %>
      <% end %>
    <% end %>
    <!-- other_fishing_trips に 主催者でなく、ステータスが'approved'と'declined'ではないやつを入れる-->
    <% other_fishing_trips = @other_trips.select { |trip| current_user != trip.organizer && @user_participation_status[trip.id] != 'approved' && @user_participation_status[trip.id] != 'declined' && @user_participation_status[trip.id] != 'pending' } %>
    
    <% if other_fishing_trips.any? %>
    
      
      <!-- テーブルの表示 -->
      <table class="table table-light table-hover">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>詳細</th>
          <th>開催場所</th>
          <th>開催日</th>
          <th>募集者</th>
          <th>現在の参加人数</th>
          <th>参加申請ボタン</th>
        </tr>
      </thead>
    
      <tbody>
        <% other_fishing_trips.each do |fishing_trip| %>
          <% if current_user != fishing_trip.organizer && @user_participation_status[fishing_trip.id] != 'approved' && @user_participation_status[fishing_trip.id] != 'declined' %>
            <tr>
              <td><%= fishing_trip.title %></td>
              <td><%= fishing_trip.description %></td>
              <td><%= fishing_trip.location %></td>
              <td><%= fishing_trip.start_date %></td>
              <td>
                  <%= link_to fishing_trip.organizer.username, user_profile_path(fishing_trip.organizer) %>
              </td>
              
              <td class="参加人数">
                <% approved_participants_count = fishing_trip.participations.where(status: 'approved').count %>
                <%= "#{approved_participants_count}/#{fishing_trip.participant_limit}" %>
              </td>
              <td class="参加状況">
                <% if @user_participation_status[fishing_trip.id] == 'pending' %>
                  承認待ち
                <% elsif approved_participants_count >= fishing_trip.participant_limit %>
                  満員🙇
                <% else %>
                  <%= form_with url: participations_path, method: :post, class: "d-inline" do |form| %>
                    <%= form.hidden_field :fishing_trip_id, value: fishing_trip.id %>
                    <%= form.submit '参加する', class: 'btn btn-primary' %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <% else %>
      <p>募集はありません。</p>
    <% end %>
  </div>
  
  <div class="tab-pane fade mt-3" id="pending-fishing-trips">
    <h2>参加申請中</h2>
    <% pending_fishing_trips = @fishing_trips.select { |trip| @user_participation_status[trip.id] == 'pending' } %>
    <% if pending_fishing_trips.any? %>
      <!-- テーブルの表示 -->
        <table class="table table-light table-hover">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>詳細</th>
            <th>開催場所</th>
            <th>開催日</th>
            <th>募集者</th>
            <th>現在の参加人数</th>
            <th>申請状況</th>
          </tr>
        </thead>
        <tbody>
          <% pending_fishing_trips.each do |fishing_trip| %>
            <tr>
              <td><%= fishing_trip.title %></td>
              <td><%= fishing_trip.description %></td>
              <td><%= fishing_trip.location %></td>
              <td><%= fishing_trip.start_date %></td>
              <td><%= link_to fishing_trip.organizer.username, user_profile_path(fishing_trip.organizer) %></td>
              <td>
                <% approved_participants_count = fishing_trip.participations.where(status: 'approved').count %>
                <%= "#{approved_participants_count}/#{fishing_trip.participant_limit}" %>
              </td>
              <td>
                承認待ち
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>参加申請はありません</p>
    <% end %>
  </div>
  
  <div class="tab-pane fade mt-3" id="approved-fishing-trips">
    <h2>参加予定</h2>
    <% approved_fishing_trips = @fishing_trips.select { |trip| @user_participation_status[trip.id] == 'approved' } %>
    
    <% if approved_fishing_trips.any? %>
      <!-- テーブルの表示 -->
        <table class="table table-light table-hover">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>詳細</th>
            <th>開催場所</th>
            <th>開催日</th>
            <th>募集者</th>
            <th>現在の参加人数</th>
            <th>キャンセル</th>
          </tr>
        </thead>
        <tbody>
          <% approved_fishing_trips.each do |fishing_trip| %>
            <tr>
              <td><%= fishing_trip.title %></td>
              <td><%= fishing_trip.description %></td>
              <td><%= fishing_trip.location %></td>
              <td><%= fishing_trip.start_date %></td>
              <td><%= link_to fishing_trip.organizer.username, user_profile_path(fishing_trip.organizer) %></td>
              <td>
                <% approved_participants_count = fishing_trip.participations.where(status: 'approved').count %>
                <%= "#{approved_participants_count}/#{fishing_trip.participant_limit}" %>
              </td>
              <td>
                <!-- キャンセル -->
                <% participation = @current_user_participations[fishing_trip.id].find { |p| p.user_id == current_user.id && p.status == 'approved' } %>
                <% if participation %>
                  <%= form_with url: participation_path(participation), method: :patch do |form| %>
                    <%= form.hidden_field :status, value: 'cancelled' %>
                    <%= form.submit 'キャンセル', class: 'btn btn-success' %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>参加予定の募集はありません。</p>
    <% end %>
  </div>
  
  
  <div class="tab-pane fade mt-3" id="my-fishing-trips">
    <h2>自分の出した釣り募集一覧</h2>
    <% my_fishing_trips = @fishing_trips.select { |trip| @is_organizer[trip.id] } %>
    
    <% if my_fishing_trips.any? %>
      <!-- テーブルの表示 -->
      <table class="table table-light table-hover">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>詳細</th>
          <th>開催場所</th>
          <th>開催日</th>
          <th>応募者</th>
          <th>参加者</th>
          <th>チャット</th>
          <th>現在の参加者数</th>
          <th>キャンセル</th>
        </tr>
      </thead>
      <% my_fishing_trips.each do |fishing_trip| %>
        <% if @is_organizer[fishing_trip.id] %>
          <tbody>
            <tr>
              <td><%= fishing_trip.title %></td>
              <td><%= fishing_trip.description %></td>
              <td><%= fishing_trip.location %></td>
              <td><%= fishing_trip.start_date %></td>
    
              <td class="応募者">
                <% @each_all_participations[fishing_trip.id].each do |participation| %>
                  <% if participation.pending? %>
                    <div class="d-flex">
                      <% if participation.status == 'pending' || participation.status == 'approved' %>
                        <%= link_to participation.user.username, user_profile_path(participation.user) %>
                        <% if participation.pending? %>
                          <%= form_with url: participation_path(participation), method: :patch do |form| %>
                            <%= form.hidden_field :status, value: 'approved' %>
                            <%= form.submit '承認', class: 'btn btn-success btn-sm' %>
                          <% end %>
                          <%= form_with url: participation_path(participation), method: :patch do |form| %>
                            <%= form.hidden_field :status, value: 'declined' %>
                            <%= form.submit '却下', class: 'btn btn-danger btn-sm' %>
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              </td>
              <td class="参加者">
                <% @each_all_participations[fishing_trip.id].each do |participation| %>
                  <% if participation.approved? %>
                    <%= link_to participation.user.username, user_profile_path(participation.user) %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if fishing_trip.chat_room %>
                  <%= link_to chat_room_path(fishing_trip.chat_room) do %>
                    <i class="bi bi-chat-dots"></i>
                  <% end %>
                <% end %>
              </td>
              <td class="参加人数">
                <% approved_participants_count = fishing_trip.participations.where(status: 'approved').count %>
                <%= "#{approved_participants_count}/#{fishing_trip.participant_limit}" %>
              </td>
              <td>
                <%= link_to '削除', fishing_trip_path(fishing_trip), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
              </td>
            </tr>
          </tbody>
        <% end %>
      <% end %>
    </table>
    <% else %>
      <p>出した募集はありません。</p>
    <% end %>
    <div class="d-flex justify-content-end">
      <%= link_to '新規募集を出す', new_fishing_trip_path, class: 'btn btn-primary' %></div>
    </div>
  </div>

</div>

app/views/fishing_trips/new.html.erb
<div class="container mt-5">
    <h1>新規募集作成</h1>
    <%= form_with(model: @fishing_trip, local: true) do |form| %>
        <% if @fishing_trip.errors.any? %>
            <div id="error_explanation">
                <div id="error_explanation" class="alert alert-danger">
                    <h2><%= pluralize(@fishing_trip.errors.count, "error") %></h2>
                    
                    <ul>
                        <% @fishing_trip.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        <% end %>
        
        
        <div class="form-group">
            <%= form.label :title, 'タイトル' %>
            <%= form.text_field :title, class: 'form-control' %>
        </div>
        
        <div class="form-group">
            <%= form.label :description, '詳細' %>
            <%= form.text_area :description, class: 'form-control' %>
        </div>
        
          <!-- 都道府県のドロップダウンメニュー -->
        <div class="form-group">
            <%= form.label :location, '開催場所' %>
            <%= form.select :location, [
              '北海道', '青森県', '岩手県', '宮城県', '秋田県', 
              '山形県', '福島県', '茨城県', '栃木県', '群馬県', 
              '埼玉県', '千葉県', '東京都', '神奈川県', '新潟県', 
              '富山県', '石川県', '福井県', '山梨県', '長野県', 
              '岐阜県', '静岡県', '愛知県', '三重県', '滋賀県', 
              '京都府', '大阪府', '兵庫県', '奈良県', '和歌山県', 
              '鳥取県', '島根県', '岡山県', '広島県', '山口県', 
              '徳島県', '香川県', '愛媛県', '高知県', '福岡県', 
              '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県', 
              '鹿児島県', '沖縄県'
            ], {}, {class: 'form-control'} %>
        </div>
        
        <div class="form-group">
            <%= form.label :start_date, '開催日' %>
            <%= form.date_select :start_date, {}, {class: 'form-control'} %>
        </div>
        
        <!-- 参加上限人数のフィールド追加 -->
        <div class="form-group">
            <%= form.label :participant_limit, '参加人数の設定' %>
            <%= form.number_field :participant_limit, in:1..100, class: 'form-control' %>
        </div>
        
        
        <div class="d-flex mt-3 justify-content-end">
            <div class="actions">
                <%= form.submit '新規募集を作成する', class: 'btn btn-primary' %>
            </div>
            <div class="actions">
                <%= link_to 'キャンセル', fishing_trips_path , class: 'btn btn-secondary ml-2'%>
            </div>
        </div>
    <% end %>
</div>